riemann:
  host: 127.0.0.1
  port: 5555
  proto: auto # auto use tcp + udp(max size 16384), tcp - tcp only
  interval: 60 # update interval for all plugins 
  use_fqdn: true
  test_connect_on_start: true
  responder:
    port: 55755

logger:
  level: DEBUG
  date_time_format: '%Y-%m-%d %H:%M:%S'

plugins:

  dummy:
    service: keep alive

  la:
    service: la
    states:
      warning: 4
      critical: 10

  disk:
    service: disk
    states:
      warning: 70
      critical: 85

  cpu:
    service: cpu usage
    states:
      warning: 0.7
      critical: 0.85

  memory:
    service: memory
    states:
      warning: 70
      critical: 85

  net:
    service: net

  cpufan:
    service: cpufan

  cputemp:
    service: cputemp

  exim4:
    service: exim4

  mdadm:
    service: mdadm

  megacli:
    service: megacli

  twcli:
    interval: 300

  nginx:
    service: nginx

  runit:
    service: runit
